User.create!({:email => "dan.rempel0@gmail.com", :password => "P@ssw0rd", :password_confirmation => "P@ssw0rd" })

Post.create(title: 'DevOps For Rails Noobs', subtitle: 'Getting your app set up on a VPS with Ubuntu 15.10, Unicorn, and Nginx.', tag_list: 'Ubuntu, DevOps, VPS', published: true, content: 'Lumbersexual vegan fanny pack listicle, sustainable asymmetrical selfies tattooed next level tote bag hammock irony. Franzen offal raw denim portland migas vice. Mixtape jean shorts austin, letterpress sustainable bespoke yr whatever fixie. Seitan flannel umami flexitarian squid, hashtag shabby chic slow-carb wayfarers chia next level. Pabst chambray pork belly, [stumptown skateboard brunch gastropub](#) cardigan truffaut forage roof party vegan street art. Vinyl single-origin coffee meggings normcore. Kombucha cliche farm-to-table chambray bitters fingerstache, locavore hashtag try-hard affogato asymmetrical.

	Migas knausgaard hammock keffiyeh readymade church-key, tousled paleo cornhole chia pickled etsy selfies. Knausgaard tacos freegan venmo, skateboard small batch chicharrones polaroid. Celiac street art distillery stumptown. Single-origin coffee lomo direct trade, slow-carb four loko stumptown kitsch roof party godard humblebrag DIY ethical quinoa mumblecore. Taxidermy paleo master cleanse next level leggings, sartorial flexitarian bitters. Mixtape flexitarian quinoa 8-bit tote bag food truck, humblebrag brunch. Knausgaard readymade schlitz, tousled flexitarian gastropub food truck vegan man braid pitchfork slow-carb asymmetrical butcher cliche kombucha.')

Post.create(title: 'Gaining Context: Hack Your Learning', subtitle: 'Hack your learning process by gaining context on Ruby on Rails and Web Development.', tag_list: 'Motivation, Learning', published: true, content: 'Lumbersexual vegan fanny pack listicle, sustainable asymmetrical selfies tattooed next level tote bag hammock irony. Franzen offal raw denim portland migas vice. Mixtape jean shorts austin, letterpress sustainable bespoke yr whatever fixie. Seitan flannel umami flexitarian squid, hashtag shabby chic slow-carb wayfarers chia next level. Pabst chambray pork belly, [stumptown skateboard brunch gastropub](#) cardigan truffaut forage roof party vegan street art. Vinyl single-origin coffee meggings normcore. Kombucha cliche farm-to-table chambray bitters fingerstache, locavore hashtag try-hard affogato asymmetrical.

  Migas knausgaard hammock keffiyeh readymade church-key, tousled paleo cornhole chia pickled etsy selfies. Knausgaard tacos freegan venmo, skateboard small batch chicharrones polaroid. Celiac street art distillery stumptown. Single-origin coffee lomo direct trade, slow-carb four loko stumptown kitsch roof party godard humblebrag DIY ethical quinoa mumblecore. Taxidermy paleo master cleanse next level leggings, sartorial flexitarian bitters. Mixtape flexitarian quinoa 8-bit tote bag food truck, humblebrag brunch. Knausgaard readymade schlitz, tousled flexitarian gastropub food truck vegan man braid pitchfork slow-carb asymmetrical butcher cliche kombucha.')

Post.create(title: 'Tutorial: Build A Simple Twitter Bot With Rails 4', subtitle: 'Have some fun with the Twitter API and the whenever gem.', tag_list: 'Tutorial, Twitter, API', published: true, content: 'Lumbersexual vegan fanny pack listicle, sustainable asymmetrical selfies tattooed next level tote bag hammock irony. Franzen offal raw denim portland migas vice. Mixtape jean shorts austin, letterpress sustainable bespoke yr whatever fixie. Seitan flannel umami flexitarian squid, hashtag shabby chic slow-carb wayfarers chia next level. Pabst chambray pork belly, [stumptown skateboard brunch gastropub](#) cardigan truffaut forage roof party vegan street art. Vinyl single-origin coffee meggings normcore. Kombucha cliche farm-to-table chambray bitters fingerstache, locavore hashtag try-hard affogato asymmetrical.

  Migas knausgaard hammock keffiyeh readymade church-key, tousled paleo cornhole chia pickled etsy selfies. Knausgaard tacos freegan venmo, skateboard small batch chicharrones polaroid. Celiac street art distillery stumptown. Single-origin coffee lomo direct trade, slow-carb four loko stumptown kitsch roof party godard humblebrag DIY ethical quinoa mumblecore. Taxidermy paleo master cleanse next level leggings, sartorial flexitarian bitters. Mixtape flexitarian quinoa 8-bit tote bag food truck, humblebrag brunch. Knausgaard readymade schlitz, tousled flexitarian gastropub food truck vegan man braid pitchfork slow-carb asymmetrical butcher cliche kombucha.')

Post.create(title: 'Tiers Of Understanding', subtitle: 'Realizing you know more than you did last week is exciting.', tag_list: 'Motivation', published: false, content: 'Lumbersexual vegan fanny pack listicle, sustainable asymmetrical selfies tattooed next level tote bag hammock irony. Franzen offal raw denim portland migas vice. Mixtape jean shorts austin, letterpress sustainable bespoke yr whatever fixie. Seitan flannel umami flexitarian squid, hashtag shabby chic slow-carb wayfarers chia next level. Pabst chambray pork belly, [stumptown skateboard brunch gastropub](#) cardigan truffaut forage roof party vegan street art. Vinyl single-origin coffee meggings normcore. Kombucha cliche farm-to-table chambray bitters fingerstache, locavore hashtag try-hard affogato asymmetrical.

  Migas knausgaard hammock keffiyeh readymade church-key, tousled paleo cornhole chia pickled etsy selfies. Knausgaard tacos freegan venmo, skateboard small batch chicharrones polaroid. Celiac street art distillery stumptown. Single-origin coffee lomo direct trade, slow-carb four loko stumptown kitsch roof party godard humblebrag DIY ethical quinoa mumblecore. Taxidermy paleo master cleanse next level leggings, sartorial flexitarian bitters. Mixtape flexitarian quinoa 8-bit tote bag food truck, humblebrag brunch. Knausgaard readymade schlitz, tousled flexitarian gastropub food truck vegan man braid pitchfork slow-carb asymmetrical butcher cliche kombucha.')

Project.create(title: 'Rempel on Rails', description: 'Lumbersexual vegan fanny pack listicle, sustainable asymmetrical selfies tattooed next level tote bag hammock irony. Franzen offal raw denim portland migas vice. Mixtape jean shorts austin, letterpress sustainable bespoke yr whatever fixie. Seitan flannel umami flexitarian squid, hashtag shabby chic slow-carb wayfarers chia next level. [Pabst chambray pork belly](#), stumptown skateboard brunch gastropub cardigan truffaut forage roof party vegan street art. Vinyl single-origin coffee meggings normcore. Kombucha cliche farm-to-table chambray bitters fingerstache, locavore hashtag try-hard affogato asymmetrical.')
Project.create(title: 'Hobbit Meal Clock', description: 'Migas knausgaard hammock keffiyeh readymade church-key, tousled paleo cornhole chia pickled etsy selfies. Knausgaard tacos freegan venmo, skateboard small batch chicharrones polaroid. Celiac street art distillery stumptown. Single-origin coffee lomo direct trade, slow-carb four loko stumptown kitsch roof party godard humblebrag [DIY ethical quinoa mumblecore](#). Taxidermy paleo master cleanse next level leggings, sartorial flexitarian bitters. Mixtape flexitarian quinoa 8-bit tote bag food truck, humblebrag brunch. Knausgaard readymade schlitz, tousled flexitarian gastropub food truck vegan man braid pitchfork slow-carb asymmetrical butcher cliche kombucha.')